#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ptolemaeus =						\
	papers/ptolemaeus/packages.tex					\
	papers/ptolemaeus/main.tex					\
	papers/ptolemaeus/references.bib				\
	papers/ptolemaeus/teil0.tex					\
	papers/ptolemaeus/teil1.tex					\
	papers/ptolemaeus/teil2.tex					\
	papers/ptolemaeus/teil3.tex

