#
# Makefile.inc -- Makefile dependencies for chapter 4
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/040-operatoren/1-pseudodifferential.tex		\
	chapters/040-operatoren/2-casimir.tex				\
	chapters/040-operatoren/chapter.tex
