#
# Makefile.inc -- Makefile dependencies for chapter 4
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/040-operatoren/1-definition.tex			\
	chapters/040-operatoren/2-laplace.tex				\
	chapters/040-operatoren/3-casimir.tex				\
	chapters/040-operatoren/4-vollstaendig.tex			\
	chapters/040-operatoren/chapter.tex
