#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/020-orthofkt/1-trigo.tex				\
	chapters/020-orthofkt/2-sa.tex					\
	chapters/020-orthofkt/3-sturmliouville.tex			\
	chapters/020-orthofkt/4-pde.tex					\
	chapters/020-orthofkt/chapter.tex
