#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-opt =						\
	papers/opt/packages.tex					\
	papers/opt/main.tex					\
	papers/opt/references.bib				\
	papers/opt/teil0.tex					\
	papers/opt/teil1.tex					\
	papers/opt/teil2.tex					\
	papers/opt/teil3.tex

