#
# Makefile.inc -- dependencies for the paper opt
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

dependencies-opt =				\
	papers/opt/packages.tex		\
	papers/opt/main.tex			\
	papers/opt/references.bib	\
	papers/opt/anwendungen.tex	\
	papers/opt/filter.tex		\
	papers/opt/grundlagen.tex	\
	papers/opt/versuch.tex      \
