#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-autotune =						\
	papers/autotune/packages.tex					\
	papers/autotune/main.tex					\
	papers/autotune/references.bib				\
	papers/autotune/teil0.tex					\
	papers/autotune/teil1.tex					\
	papers/autotune/teil2.tex					\
	papers/autotune/teil3.tex

