#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-autotune =							\
	papers/autotune/packages.tex					\
	papers/autotune/main.tex					\
	papers/autotune/references.bib					\
	papers/autotune/00_Einleitung.tex				\
	papers/autotune/01_Pitch_Detektion.tex				\
	papers/autotune/02_Pitch_Tonsystem_und_Stimmung.tex		\
	papers/autotune/03_Pitch_Korrektur.tex				\
	papers/autotune/04_Fazit.tex
