#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ct =						\
	papers/ct/packages.tex					\
	papers/ct/main.tex					\
	papers/ct/references.bib				\
	papers/ct/teil0.tex					\
	papers/ct/teil1.tex					\
	papers/ct/teil2.tex					\
	papers/ct/teil3.tex

