#
# Makefile.inc -- Makefile dependencies for chapter 0
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/000-einleitung/chapter.tex				\
	chapters/000-einleitung/inhalt.tex
