#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-brown =						\
	papers/brown/packages.tex					\
	papers/brown/main.tex					\
	papers/brown/references.bib				\
	papers/brown/teil0.tex					\
	papers/brown/teil1.tex					\
	papers/brown/teil2.tex					\
	papers/brown/teil3.tex

