#
# Makefile
#
# (c) 2023 Prof Dr Andreas Müller
#
all:	f23.pdf f32.pdf f30.pdf

f23.pdf:	f23.tex fcommon.tex
	pdflatex f23.tex

f32.pdf:	f32.tex fcommon.tex
	pdflatex f32.tex

f30.pdf:	f30.tex
	pdflatex f30.tex

