#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-spektral =						\
	papers/spektral/packages.tex					\
	papers/spektral/main.tex					\
	papers/spektral/references.bib				\
	papers/spektral/teil0.tex					\
	papers/spektral/teil1.tex					\
	papers/spektral/teil2.tex					\
	papers/spektral/teil3.tex

