#
# Makefile.inc -- dependencies for this article
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-spektral =							\
	papers/spektral/packages.tex					\
	papers/spektral/main.tex					\
	papers/spektral/references.bib					\
	papers/spektral/00_Einleitung.tex				\
	papers/spektral/01_NWP.tex					\
	papers/spektral/02_SpektralModelle.tex	

