#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-mellin =						\
	papers/mellin/packages.tex					\
	papers/mellin/main.tex					\
	papers/mellin/references.bib				\
	papers/mellin/teil0.tex					\
	papers/mellin/teil1.tex					\
	papers/mellin/teil2.tex					\
	papers/mellin/teil3.tex

