#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/060-diskret/1-endlich.tex				\
	chapters/060-diskret/2-aufloesung.tex				\
	chapters/060-diskret/3-schnell.tex				\
	chapters/060-diskret/4-koerper.tex				\
	chapters/060-diskret/chapter.tex
