#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/060-diskret/1-endlich.tex				\
	chapters/060-diskret/chapter.tex
