#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/060-diskret/1-endlich.tex				\
	chapters/060-diskret/2-tensor.tex				\
	chapters/060-diskret/3-faktorisierung.tex			\
	chapters/060-diskret/31-interpolation.tex			\
	chapters/060-diskret/32-vandermonde.tex				\
	chapters/060-diskret/33-faktorisierung.tex			\
	chapters/060-diskret/34-Apq.tex					\
	chapters/060-diskret/35-Fpq.tex					\
	chapters/060-diskret/36-faktorisierung.tex			\
	chapters/060-diskret/4-schnell.tex				\
	chapters/060-diskret/5-koerper.tex				\
	chapters/060-diskret/chapter.tex
