#
# Makefile
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	parallelogramm.pdf						\
	fourierrechteck.pdf						\
	fourierdreieck.pdf						\
	kreise.pdf							\
	dreieck.pdf							\
	wurzel.pdf							\
	l1konvergenz.pdf						\
	normbeispiele.pdf						\
	schwach.pdf

parallelogramm.pdf:	parallelogramm.tex
	pdflatex parallelogramm.tex

fourierrechteck.pdf:	fourierrechteck.tex
	pdflatex fourierrechteck.tex

fourierdreieck.pdf:	fourierdreieck.tex
	pdflatex fourierdreieck.tex

kreise.pdf:	kreise.tex
	pdflatex kreise.tex

dreieck.pdf:	dreieck.tex
	pdflatex dreieck.tex

wurzel.pdf:	wurzel.tex
	pdflatex wurzel.tex

l1konvergenz.pdf:	l1konvergenz.tex
	pdflatex l1konvergenz.tex

normbeispiele.pdf:	normbeispiele.tex
	pdflatex normbeispiele.tex

schwach.pdf:	schwach.tex
	pdflatex schwach.tex

