#
# Makefile
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	parallelogramm.pdf fourierrechteck.pdf fourierdreieck.pdf

parallelogramm.pdf:	parallelogramm.tex
	pdflatex parallelogramm.tex

fourierrechteck.pdf:	fourierrechteck.tex
	pdflatex fourierrechteck.tex

fourierdreieck.pdf:	fourierdreieck.tex
	pdflatex fourierdreieck.tex
