#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ml =						\
	papers/ml/packages.tex					\
	papers/ml/main.tex					\
	papers/ml/references.bib				\
	papers/ml/0_einleitung.tex					\
	papers/ml/1_lineare_regression.tex					\

