#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ml =						\
	papers/ml/packages.tex					\
	papers/ml/main.tex					\
	papers/ml/references.bib				\
	papers/ml/teil0.tex					\
	papers/ml/teil1.tex					\
	papers/ml/teil2.tex					\
	papers/ml/teil3.tex

