#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/010-skalarprodukt/1-definition.tex			\
	chapters/010-skalarprodukt/2-cauchyschwarz.tex			\
	chapters/010-skalarprodukt/3-funktionenraeume.tex		\
	chapters/010-skalarprodukt/4-hilbertraum.tex			\
	chapters/010-skalarprodukt/5-sobolevraum.tex			\
	chapters/010-skalarprodukt/chapter.tex
