#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/010-skalarprodukt/1-definition.tex			\
	chapters/010-skalarprodukt/chapter.tex
