#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-gezeiten =						\
	papers/gezeiten/packages.tex					\
	papers/gezeiten/main.tex					\
	papers/gezeiten/references.bib				\
	papers/gezeiten/teil0.tex					\
	papers/gezeiten/teil1.tex					\
	papers/gezeiten/teil2.tex					\
	papers/gezeiten/teil3.tex

