#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-sonogramm =						\
	papers/sonogramm/packages.tex					\
	papers/sonogramm/main.tex					\
	papers/sonogramm/references.bib				\
	papers/sonogramm/teil0.tex					\
	papers/sonogramm/teil1.tex					\
	papers/sonogramm/teil2.tex					\
	papers/sonogramm/teil3.tex

