#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/030-gruppen/1-gruppe.tex				\
	chapters/030-gruppen/11-definition.tex				\
	chapters/030-gruppen/12-endlich.tex				\
	chapters/030-gruppen/13-lie.tex					\
	chapters/030-gruppen/14-funktionenaufg.tex			\
	chapters/030-gruppen/2-haar.tex					\
	chapters/030-gruppen/3-faltung.tex				\
	chapters/030-gruppen/4-gelfand.tex				\
	chapters/030-gruppen/5-fourier.tex				\
	chapters/030-gruppen/6-darstellung.tex				\
	chapters/030-gruppen/61-definition.tex				\
	chapters/030-gruppen/62-rechnen.tex				\
	chapters/030-gruppen/63-vergleich.tex				\
	chapters/030-gruppen/64-schur.tex				\
	chapters/030-gruppen/65-charakter.tex				\
	chapters/030-gruppen/66-mittelung.tex				\
	chapters/030-gruppen/67-relationen.tex				\
	chapters/030-gruppen/68-orthochar.tex				\
	chapters/030-gruppen/69-orthouni.tex				\
	chapters/030-gruppen/6a-lie.tex					\
	chapters/030-gruppen/6b-regulaer.tex				\
	chapters/030-gruppen/7-abelschegruppen.tex			\
	chapters/030-gruppen/uebungsaufgaben/301.tex			\
	chapters/030-gruppen/chapter.tex
