#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/030-gruppen/1-gruppe.tex				\
	chapters/030-gruppen/2-haar.tex					\
	chapters/030-gruppen/3-faltung.tex				\
	chapters/030-gruppen/4-gelfand.tex				\
	chapters/030-gruppen/5-fourier.tex				\
	chapters/030-gruppen/6-darstellung.tex				\
	chapters/030-gruppen/7-matrixelemente.tex			\
	chapters/030-gruppen/8-charaktere.tex				\
	chapters/030-gruppen/uebungsaufgaben/301.tex			\
	chapters/030-gruppen/chapter.tex
