#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-milankovic =						\
	papers/milankovic/packages.tex					\
	papers/milankovic/main.tex					\
	papers/milankovic/references.bib				\
	papers/milankovic/teil0.tex					\
	papers/milankovic/teil1.tex					\
	papers/milankovic/teil2.tex					\
	papers/milankovic/teil3.tex

