#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-milankovic =						\
	papers/milankovic/packages.tex					\
	papers/milankovic/main.tex					\
	papers/milankovic/references.bib				\
	papers/milankovic/teil0_Einleitung.tex				\
	papers/milankovic/teil1_VorstellungderMilankovic-Zyklen.tex	\
	papers/milankovic/teil2_WissenschaftlicheArbeit.tex		\
	papers/milankovic/teil3_Konklusion.tex

