#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/070-nichtkomm/1-beispiele.tex				\
	chapters/070-nichtkomm/chapter.tex
