#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/070-nichtkomm/1-motivation.tex				\
	chapters/070-nichtkomm/2-homogen.tex				\
	chapters/070-nichtkomm/3-mittelung.tex				\
	chapters/070-nichtkomm/4-gelfand.tex				\
	chapters/070-nichtkomm/5-mendez.tex				\
	chapters/070-nichtkomm/6-registrierung.tex			\
	chapters/070-nichtkomm/chapter.tex
