#
# Makefile.inc
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter0 = 								\
	../slides/0/frueher.tex						\
	../slides/0/info.tex						\
	../slides/0/jwst.tex						\
	../slides/0/radon.tex						\
	../slides/0/regis.tex						\
	../slides/0/spektrum.tex					\
	../slides/0/was.tex
