#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-wavelets =						\
	papers/wavelets/packages.tex					\
	papers/wavelets/main.tex					\
	papers/wavelets/references.bib				\
	papers/wavelets/teil0.tex					\
	papers/wavelets/teil1.tex					\
	papers/wavelets/teil2.tex					\
	papers/wavelets/teil3.tex	\
	papers/wavelets/teil4.tex	\
	papers/wavelets/teil5.tex	\
	papers/wavelets/teil6.tex
