#
# Makefile -- build images
#
# (c) 2023 Prof Dr Andreas Müller
#
all: triangle_truncation.pdf forward_difference.pdf spherical_coordinates.pdf

triangle_truncation.pdf: triangle_truncation.pdf
	pdflatex triangle_truncation.tex

forward_difference.pdf:	forward_difference.tex
	pdflatex forward_difference.tex

spherical_coordinates.pdf: spherical_coordinates.tex
	pdflatex spherical_coordinates.tex