#
# Makefile.inc -- Makefile dependencies for chapter 5
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/050-radon/1-definition.tex				\
	chapters/050-radon/2-ableitungen.tex				\
	chapters/050-radon/3-rueckprojektion.tex			\
	chapters/050-radon/chapter.tex
