#
# Makefile.inc -- Makefile dependencies for chapter 5
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/050-radon/1-definition.tex				\
	chapters/050-radon/2-rueckprojektion.tex			\
	chapters/050-radon/3-bild.tex					\
	chapters/050-radon/4-dgl.tex					\
	chapters/050-radon/chapter.tex
