#!/usr/bin/env bash
#
# mkpapers -- this script builds the paper inclusion commands
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
awk 'BEGIN {
	printf("%%\n")
	printf("%% addpapers.tex -- file to add all paper main files\n")
	printf("%%\n")
	printf("%% (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule\n")
	printf("%%\n")
}
{
	printf("\\input{papers/%s/main.tex}\n", $1)
}' common/paperlist > common/addpapers.tex

