#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-jpeg =						\
	papers/jpeg/packages.tex				\
	papers/jpeg/main.tex					\
	papers/jpeg/references.bib				\
	papers/jpeg/00_Einleitung.tex				\
	papers/jpeg/01_DCT.tex					\
	papers/jpeg/02_JPEG.tex					\
	papers/jpeg/03_WT.tex					\
	papers/jpeg/04_JPEG2000.tex

