#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-jpeg =						\
	papers/jpeg/packages.tex					\
	papers/jpeg/main.tex					\
	papers/jpeg/references.bib				\
	papers/jpeg/teil0.tex					\
	papers/jpeg/teil1.tex					\
	papers/jpeg/teil2.tex					\
	papers/jpeg/teil3.tex

